from app.crud.user import eliminar_usuario,create_user,get_user_by_email,get_password_hash,update_user_password,validate_password
from app.crud.muestra_de_leche import actualizar_muestra,crear_muestra,ver_muestras_por_fecha
from app.crud.analisis_de_muestra import  generar_analisis, ver_analisis
from app.crud.formulario_ingreso import actualizar_formulario, crear_formulario, eliminar_formulario, ver_formulario