"""crear tablas iniciales

Revision ID: 14412b216ee9
Revises: d34ee26ef652
Create Date: 2025-05-16 21:24:37.213137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14412b216ee9'
down_revision: Union[str, None] = 'd34ee26ef652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('email', sa.String(), nullable=False))
    op.add_column('usuarios', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column('usuarios', sa.Column('full_name', sa.String(), nullable=False))
    op.drop_constraint('usuarios_correo_key', 'usuarios', type_='unique')
    op.create_unique_constraint(None, 'usuarios', ['email'])
    op.drop_column('usuarios', 'correo')
    op.drop_column('usuarios', 'contrasena')
    op.drop_column('usuarios', 'nombre')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('usuarios', sa.Column('contrasena', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('usuarios', sa.Column('correo', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.create_unique_constraint('usuarios_correo_key', 'usuarios', ['correo'], postgresql_nulls_not_distinct=False)
    op.drop_column('usuarios', 'full_name')
    op.drop_column('usuarios', 'hashed_password')
    op.drop_column('usuarios', 'email')
    # ### end Alembic commands ###
