"""crear tablas iniciales

Revision ID: d34ee26ef652
Revises: 
Create Date: 2025-05-16 21:12:09.027468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd34ee26ef652'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('contrasena', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo')
    )
    op.create_index(op.f('ix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False)
    op.create_table('formularios_ingreso',
    sa.Column('id_f_ingreso', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_mama', sa.String(), nullable=False),
    sa.Column('nombre_bebe', sa.String(), nullable=False),
    sa.Column('sexo_bebe', sa.String(), nullable=False),
    sa.Column('edad_mama', sa.Integer(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('semanas_del_parto', sa.Integer(), nullable=False),
    sa.Column('prematuro', sa.Boolean(), nullable=False),
    sa.Column('numero_de_parto', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Integer(), nullable=False),
    sa.Column('tamaño', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_f_ingreso'),
    sa.UniqueConstraint('id_usuario')
    )
    op.create_index(op.f('ix_formularios_ingreso_id_f_ingreso'), 'formularios_ingreso', ['id_f_ingreso'], unique=False)
    op.create_table('muestras',
    sa.Column('id_muestra', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_f_ingreso', sa.Integer(), nullable=False),
    sa.Column('nombre_muestra', sa.String(), nullable=False),
    sa.Column('fecha_de_extraccion', sa.Date(), nullable=False),
    sa.Column('hora_de_extraccion', sa.Time(), nullable=False),
    sa.Column('volumen', sa.Float(), nullable=False),
    sa.Column('pecho', sa.String(), nullable=False),
    sa.Column('color', sa.Enum('blanco', 'amarillento', 'transparente', name='colormuestra'), nullable=False),
    sa.Column('ubicacion', sa.Enum('refrigerador', 'congelador', 'banco_de_leche', name='ubicacionmuestra'), nullable=False),
    sa.Column('observacion', sa.String(), nullable=True),
    sa.Column('foto_de_muestra', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_f_ingreso'], ['formularios_ingreso.id_f_ingreso'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_muestra')
    )
    op.create_index(op.f('ix_muestras_id_muestra'), 'muestras', ['id_muestra'], unique=False)
    op.create_table('analisis',
    sa.Column('id_analisis', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_f_ingreso', sa.Integer(), nullable=False),
    sa.Column('id_muestra', sa.Integer(), nullable=False),
    sa.Column('ph', sa.Float(), nullable=False),
    sa.Column('conductividad', sa.Float(), nullable=False),
    sa.Column('temperatura', sa.Float(), nullable=False),
    sa.Column('mensaje_temp', sa.String(), nullable=False),
    sa.Column('tipo_de_leche', sa.Enum('calostro', 'transicional', 'madura', name='tipodeleche'), nullable=False),
    sa.ForeignKeyConstraint(['id_f_ingreso'], ['formularios_ingreso.id_f_ingreso'], ),
    sa.ForeignKeyConstraint(['id_muestra'], ['muestras.id_muestra'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_analisis')
    )
    op.create_index(op.f('ix_analisis_id_analisis'), 'analisis', ['id_analisis'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analisis_id_analisis'), table_name='analisis')
    op.drop_table('analisis')
    op.drop_index(op.f('ix_muestras_id_muestra'), table_name='muestras')
    op.drop_table('muestras')
    op.drop_index(op.f('ix_formularios_ingreso_id_f_ingreso'), table_name='formularios_ingreso')
    op.drop_table('formularios_ingreso')
    op.drop_index(op.f('ix_usuarios_id_usuario'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
